## 1. Creating Numpy Array

In [ ]:
# Importing NumPy Array
import numpy as np

# Creating an array using np.array() method
arr = np.array([10, 20, 30, 40, 50])

# Printing
print(arr) # Prints [10 20 30 40 50]

[10 20 30 40 50]


In [ ]:
# Zero Dimensions
arr = np.array(42)
print(arr)

42


In [ ]:
# one dimensions array
a = np.array([1,2,3])
print(a)

[1 2 3]


In [ ]:
# more than one dimensions
arr = np.array([[1, 2, 3], [4, 5, 6] , [7 , 8 , 9] , [10 , 11 , 12]])
print(arr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [ ]:
# Create a 3-D array with two 2-D arrays, both containing two arrays with the values 1,2,3 and 4,5,6
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]] , [[10 , 11 , 12] , [15 , 16 , 17]] , [[11 , 12 , 13] , [15 , 16 , 17]]])
print(arr)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 1  2  3]
  [ 4  5  6]]

 [[10 11 12]
  [15 16 17]]

 [[11 12 13]
  [15 16 17]]]


In [ ]:
# minimum dimensions
a = np.array([[1, 2, 3], [4, 5, 6] , [7 , 8 , 9] , [10 , 11 , 12]], ndmin = 3)
print(a)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]]]


In [ ]:
# dtype parameter
a = np.array([1, 2, 3], dtype = complex)
print(a)

[1.+0.j 2.+0.j 3.+0.j]


In [ ]:
# Type Of Array
arr = np.array([1, 2, 3, 4, 5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [ ]:
# Use a tuple to create a NumPy array
arr = np.array((1, 2, 3, 4, 5))
print(arr)

[1 2 3 4 5]


In [ ]:
# Check how many dimensions the arrays have:
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


## 2. Array Attributes

In [ ]:
# It can also be used to resize the array
a = np.array([[1,2,3],[4,5,6]])
print(a.shape)
print(a)

(2, 3)
[[1 2 3]
 [4 5 6]]


In [ ]:
# this resizes the ndarray
a = np.array([[1,2,3],[4,5,6]])
a.shape = (3,2)
print(a)
# Another Fucntion to resizes the ndarray
a = np.array([[1,2,3],[4,5,6]])
b = a.reshape(3,2)
print(b)

[[1 2]
 [3 4]
 [5 6]]
[[1 2]
 [3 4]
 [5 6]]


In [ ]:
# an array of evenly spaced numbers
a = np.arange(24)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [ ]:
# this is one dimensional array
import numpy as np
a = np.arange(24)
print(a.ndim)

# now reshape it
b = a.reshape(2,4,3)
print(b)
# b is having three dimensions

1
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]]


In [ ]:
# dtype of array is int8 (1 byte)
x = np.array([1,2,3,4,5], dtype = np.int8)
print(x.itemsize)
# dtype of array is now float32 (4 bytes)
x = np.array([1,2,3,4,5], dtype = np.float32)
print(x.itemsize)

1
4


In [ ]:
# Array Creation Routines
x = np.empty((3,3), dtype = int)
print(x)

[[97418469100951              0              0]
 [             0              0              0]
 [             0              0              0]]


In [ ]:
# array of five zeros. Default dtype is float
x = np.zeros(5)
print(x)

x = np.zeros((6,3), dtype = int)
print(x)

[0. 0. 0. 0. 0.]
[[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]


In [ ]:
# array of five ones. Default dtype is float
x = np.ones(5)
print(x)
x = np.ones((2,3), dtype = int)
print(x)

[1. 1. 1. 1. 1.]
[[1 1 1]
 [1 1 1]]


##  3. Array From Existing Data

In [ ]:
# ndarray from tuple of lists
x = ([8, 4, 6], [1, 2, 3])
a = np.asarray(x)
print(a)

x = ([8, 4, 6])
a = np.asarray(x)
print(a)


[[8 4 6]
 [1 2 3]]
[8 4 6]


In [ ]:
# ndarray from list of tuples
x = [(1, 1.1), (2, 1.2), (3, 1.3)]
a = np.asarray(x)
print(a)

[[1.  1.1]
 [2.  1.2]
 [3.  1.3]]


In [ ]:
# Using Buffer
s = b'hello world'
np.frombuffer(s, dtype='S1')

array([b'h', b'e', b'l', b'l', b'o', b' ', b'w', b'o', b'r', b'l', b'd'],
      dtype='|S1')

In [ ]:
# Using Buffer with count and offset
s = b"hello world"
np.frombuffer(s, dtype='S1', count=4, offset=6)

array([b'w', b'o', b'r', b'l'], dtype='|S1')

In [ ]:
# using Buffer
np.frombuffer(b'\x01\x02\x03\x04\x05', dtype=np.uint8, count=4)

array([1, 2, 3, 4], dtype=uint8)

In [ ]:
my_list =  (x*x for x in range(5))
# use iterator to create ndarray
x = np.fromiter(my_list, dtype = float)
print(x)
# using dtype to reshape
iterable = ((x+1, x+2 , x+3 , x+4) for x in range(5))
np.fromiter(iterable, dtype=np.dtype((int, 4)))

[ 0.  1.  4.  9. 16.]


array([[1, 2, 3, 4],
       [2, 3, 4, 5],
       [3, 4, 5, 6],
       [4, 5, 6, 7],
       [5, 6, 7, 8]])

## 4. Array Indexing

In [ ]:
# Get the first element from the following array:
arr = np.array([1, 2, 3, 4])
print(arr[0])
# Get the second element from the following array:
arr = np.array([1, 2, 3, 4])
print(arr[1])
# Get third and fourth elements from the following array and add them
arr = np.array([1, 2, 3, 4])
print(arr[2] + arr[3])

1
2
7


In [ ]:
# Access the element on the first row, second column:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print('2nd element on 1st row: ', arr[0, 1])
# Access the element on the 2nd row, 5th column:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print('5th element on 2nd row: ', arr[1, 4])
print('4th element on 1nd row: ', arr[0, 3])

2nd element on 1st row:  2
5th element on 2nd row:  10
4th element on 1nd row:  4


In [ ]:
# Access the third element of the second array of the first array:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr[0, 1, 2])
print(arr[1 , 1 , 1])

"""
arr[0, 1, 2] prints the value 6.

And this is why:

The first number represents the first dimension, which contains two arrays:
[[1, 2, 3], [4, 5, 6]]
and:
[[7, 8, 9], [10, 11, 12]]
Since we selected 0, we are left with the first array:
[[1, 2, 3], [4, 5, 6]]

The second number represents the second dimension, which also contains two arrays:
[1, 2, 3]
and:
[4, 5, 6]
Since we selected 1, we are left with the second array:
[4, 5, 6]

The third number represents the third dimension, which contains three values:
4
5
6
Since we selected 2, we end up with the third value:
6
"""

6
11


'\narr[0, 1, 2] prints the value 6.\n\nAnd this is why:\n\nThe first number represents the first dimension, which contains two arrays:\n[[1, 2, 3], [4, 5, 6]]\nand:\n[[7, 8, 9], [10, 11, 12]]\nSince we selected 0, we are left with the first array:\n[[1, 2, 3], [4, 5, 6]]\n\nThe second number represents the second dimension, which also contains two arrays:\n[1, 2, 3]\nand:\n[4, 5, 6]\nSince we selected 1, we are left with the second array:\n[4, 5, 6]\n\nThe third number represents the third dimension, which contains three values:\n4\n5\n6\nSince we selected 2, we end up with the third value:\n6\n'

In [ ]:
# Negative Indexing
# Print the last element from the 2nd dim:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print('Last element from 2nd dim: ', arr[1, -1])

Last element from 2nd dim:  10


## 5. Array **Slicing**

In [ ]:
# Slice elements from index 1 to index 5 from the following array:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[1:5])

# Slice elements from index 4 to the end of the array:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[4:])


# Slice elements from the beginning to index 4 (not included):
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[:4])

# Slice from the index 3 from the end to index 1 from the end:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[-3:-1])

# Return every other element from the entire array:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[::2])

[2 3 4 5]
[5 6 7]
[1 2 3 4]
[5 6]
[1 3 5 7]


In [ ]:
# From the second element, slice elements from index 1 to index 4 (not included):
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[1, 1:4])

# From both elements, return index 2:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[0:2, 2])

# From both elements, slice index 1 to index 4 (not included), this will return a 2-D array:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[0:2, 1:4])

[7 8 9]
[3 8]
[[2 3 4]
 [7 8 9]]


## 6. Data Types

In [ ]:
"""
i - integer
b - boolean
u - unsigned integer
f - float
c - complex float
m - timedelta
M - datetime
O - object
S - string
U - unicode string
V - fixed chunk of memory for other type (void)
"""
# Get the data type of an array containing strings:
arr = np.array(['apple', 'banana', 'cherry'])
print(arr)
print(arr.dtype)

['apple' 'banana' 'cherry']
<U6


In [ ]:
# Create an array with data type string:
arr = np.array([1, 2, 3, 4], dtype='S')
print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4']
|S1


In [ ]:
# For i, u, f, S and U we can define size as well.
# Create an array with data type 4 bytes integer:
arr = np.array([1, 2, 3, 4], dtype='i4')
print(arr)
print(arr.dtype)

[1 2 3 4]
int32


In [ ]:
# Change data type from integer to boolean:
arr = np.array([1, 0, 3 , 4 , 5 , 0 , 9])
newarr = arr.astype(bool)
print(newarr)
print(newarr.dtype)

[ True False  True  True  True False  True]
bool


## 7. Array Copy vs View

In [ ]:
# Make a copy, change the original array, and display both arrays:
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42
print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


In [ ]:
# Make a view, change the view, and display both arrays:
arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
x[0] =88
print(arr)
print(x)

[88  2  3  4  5]
[88  2  3  4  5]


In [ ]:
# Print the value of the base attribute to check if an array owns it's data or not:
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
y = arr.view()
print(x.base)
print(y.base)

None
[1 2 3 4 5]


## 8. Reshape

In [ ]:
# Reshape From 1-D to 2-D
# Convert the following 1-D array with 12 elements into a 2-D array.
#The outermost dimension will have 4 arrays, each with 3 elements:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(4, 3)
print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [ ]:
# Reshape From 1-D to 3-D
# Convert the following 1-D array with 12 elements into a 3-D array.
# The outermost dimension will have 2 arrays that contains 3 arrays, each with 2 elements:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(2, 3, 2)
print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [ ]:
# Check if the returned array is a copy or a view:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
print(arr.reshape(2, 4).base)

[1 2 3 4 5 6 7 8]


In [ ]:
# Convert 1D array with 8 elements to 3D array with 2x2 elements:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
newarr = arr.reshape(2, 2 ,-1)
print(newarr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [ ]:
# Flattening array means converting a multidimensional array into a 1D array.
# We can use reshape(-1) to do this.
# Convert the array into a 1D array:
arr = np.array([[1, 2, 3], [4, 5, 6]])
newarr = arr.reshape(-1)
print(newarr)
newarr = arr.flatten()
print(newarr)

[1 2 3 4 5 6]
[1 2 3 4 5 6]


## 9. Array Iterating

In [ ]:
# Iterate on the elements of the following 1-D array:
arr = np.array([1, 2, 3])
for x in arr:
  print(x)

1
2
3


In [ ]:
# Iterate on the elements of the following 2-D array:
arr = np.array([[1, 2, 3 , 4], [4, 5, 6 , 7]])
for x in arr:
  print(x)
print(x.shape)  # (4,) --- > One Dim has 4 Elements

[1 2 3 4]
[4 5 6 7]
(4,)


In [ ]:
# Iterate on each scalar element of the 2-D array:
arr = np.array([[1, 2, 3], [4, 5, 6]])
for x in arr:
  for y in x:
    print(y)

1
2
3
4
5
6


In [ ]:
# Iterate on the elements of the following 3-D array:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
for x in arr:
  print(x)
print(x.shape)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]
(2, 3)


In [ ]:
# Iterate down to the scalars:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
for x in arr:
  for y in x:
    for z in y:
      print(z)

1
2
3
4
5
6
7
8
9
10
11
12


In [ ]:
# Iterate through the following 3-D array:
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
for x in np.nditer(arr):
  print(x)

1
2
3
4
5
6
7
8


In [ ]:
# Iterate through the array as a string:
arr = np.array([1, 2, 3])
for x in np.nditer(arr, flags=['buffered'], op_dtypes=['S']):
  print(x)

b'1'
b'2'
b'3'


In [ ]:
# Iterate through every scalar element of the 2D array skipping 1 element:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
for x in np.nditer(arr[:, ::2]):
  print(x)

1
3
5
7


In [ ]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(arr)
print(arr[0,:])

[[1 2 3 4]
 [5 6 7 8]]
[1 2 3 4]


In [ ]:
# Enumerate on following 1D arrays elements:
arr = np.array([1, 2, 3])
for idx, x in np.ndenumerate(arr):
  print(idx, x)

(0,) 1
(1,) 2
(2,) 3


In [ ]:
# Enumerate on following 2D array's elements:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
for idx, x in np.ndenumerate(arr):
  print(idx, x)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8


## 10. Joining Array

In [ ]:
# Join two arrays
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.concatenate((arr1, arr2))
print(arr)

[1 2 3 4 5 6]


In [ ]:
# Join two 2-D arrays along rows (axis=1):
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
arr = np.concatenate((arr1, arr2) , axis=1)
print(arr)

[[1 2 5 6]
 [3 4 7 8]]


In [ ]:
# Joining Arrays Using Stack Functions:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.stack((arr1, arr2), axis=1)
print(arr)

[[1 4]
 [2 5]
 [3 6]]


In [ ]:
# NumPy provides a helper function: hstack() to stack along rows.
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.hstack((arr1, arr2))
print(arr)

[1 2 3 4 5 6]


In [ ]:
# NumPy provides a helper function: vstack() to stack along columns.

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.vstack((arr1, arr2))
print(arr)

[[1 2 3]
 [4 5 6]]


In [ ]:
# NumPy provides a helper function: dstack() to convert into third Dim.
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.dstack((arr1, arr2))
print(arr.shape)
print(arr)

(1, 3, 2)
[[[1 4]
  [2 5]
  [3 6]]]


## 11. Splitting Array

In [ ]:
# Split the array in 3 parts:
arr = np.array([1, 2, 3, 4, 5, 6])
newarr = np.array_split(arr, 3)
print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [ ]:
# Split the array in 4 parts:
arr = np.array([1, 2, 3, 4, 5, 6])
newarr = np.array_split(arr, 3)
print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [ ]:
# Access the splitted arrays:
arr = np.array([1, 2, 3, 4, 5, 6])
newarr = np.array_split(arr, 3)
print(newarr[0])
print(newarr[1])
print(newarr[2])

[1 2]
[3 4]
[5 6]


In [ ]:
# Split the 2-D array into three 2-D arrays.
arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])
newarr = np.array_split(arr, 3)
print(newarr)

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]


In [ ]:
# Split the 2-D array into three 2-D arrays.
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])
newarr = np.array_split(arr, 3)
print(newarr)

[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]]), array([[13, 14, 15],
       [16, 17, 18]])]


In [ ]:
# Split the 2-D array into three 2-D arrays along rows.
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])
newarr = np.array_split(arr, 3, axis=1)
print(arr.shape)
print(newarr)

(6, 3)
[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


## 12. Searching Arrays

In [ ]:
# Find the indexes where the value is 4:
arr = np.array([1, 2, 3, 4, 5, 4, 4])
x = np.where(arr == 4)
print(x)

(array([3, 5, 6]),)


In [ ]:
# Find the indexes where the value 7 should be inserted:
arr = np.array([6, 9, 7, 8])
x = np.searchsorted(arr, 7)
print(x)

1


## 13. Sorting Arrays

In [ ]:
# Sort the array:
arr = np.array([3, 2, 0, 1])
print(np.sort(arr))

# Sort the array alphabetically:
arr = np.array(['banana', 'cherry', 'apple'])
print(np.sort(arr))

[0 1 2 3]
['apple' 'banana' 'cherry']


In [ ]:
# Sort a 2-D array:
arr = np.array([[3, 2, 4], [5, 0, 1]])
print(np.sort(arr))

[[2 3 4]
 [0 1 5]]


## 14. Filtering Arrays

In [ ]:
# Create an array from the elements on index 0 and 2:
arr = np.array([41, 42, 43, 44])
x = [True, False, True, False]
newarr = arr[x]
print(newarr)

[41 43]


In [ ]:
# Create a filter array that will return only values higher than 42:
arr = np.array([41, 42, 43, 44])
# Create an empty list
filter_arr = []
# go through each element in arr
for element in arr:
  # if the element is higher than 42, set the value to True, otherwise False:
  if element > 42:
    filter_arr.append(True)
  else:
    filter_arr.append(False)

newarr = arr[filter_arr]
print(filter_arr)
print(newarr)

[False, False, True, True]
[43 44]


In [ ]:
# Create a filter array that will return only even elements from the original array:

arr = np.array([1, 2, 3, 4, 5, 6, 7])
# Create an empty list
filter_arr = []
# go through each element in arr
for element in arr:
  # if the element is completely divisble by 2, set the value to True, otherwise False
  if element % 2 == 0:
    filter_arr.append(True)
  else:
    filter_arr.append(False)

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False, True, False, True, False, True, False]
[2 4 6]


In [ ]:
# Create a filter array that will return only values higher than 42:
arr = np.array([41, 42, 43, 44])
filter_arr = arr > 42
newarr = arr[filter_arr]
print(filter_arr)
print(newarr)

[False False  True  True]
[43 44]


In [ ]:
# Create a filter array that will return only even elements from the original array:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
filter_arr = arr % 2 == 0
newarr = arr[filter_arr]
print(filter_arr)
print(newarr)

[False  True False  True False  True False]
[2 4 6]


## 15. Random Numbers

In [ ]:
# Generate a random integer from 0 to 100:
from numpy import random
x = random.randint(100)
print(x)

50


In [ ]:
# Generate a random float from 0 to 1:
x = random.rand()
print(x)

0.750246511755587


In [ ]:
# Generate a 1-D array containing 5 random integers from 0 to 100:
x=random.randint(10000, size=(5))
print(x)

[5626 7454 2426 2441 8568]


In [ ]:
# Generate a 2-D array with 3 rows, each row containing 5 random integers from 0 to 100:
x = random.randint(100, size=(3, 5))
print(x)

[[ 6 92 37 57 16]
 [44 49 57 71  9]
 [87 54 67 33 74]]


In [ ]:
# Return one of the values in an array:
x = random.choice([3, 5, 7, 9])
print(x)

7


In [ ]:
# Generate a 2-D array that consists of the values in the array parameter (3, 5, 7, and 9):
x = random.choice([3, 5, 7, 9, 10], size=(3, 5))
print(x)

[[ 7  3  9  7  9]
 [ 7 10  7  3  9]
 [ 3 10  7 10  3]]


In [ ]:
my_list = [3, 5, 7, 9]
print(my_list * 2)
print("#" * 20)
arr = np.array([3, 5, 7, 9])
print(arr * 2)

[3, 5, 7, 9, 3, 5, 7, 9]
####################
[ 6 10 14 18]
