In [1]:
import numpy as np

In [3]:
arr1 = [2,3,4,5]
np_arr = np.array(arr1) # converting list to numpy array

In [4]:
print(np_arr.dtype)

int64


In [6]:
# Multi dimention array
mul_arr = [[1,2,3],[4,5,6]]
np_mul_arr = np.array(mul_arr)

np_mul_arr


array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
print(np_mul_arr.shape)

(2, 3)


In [11]:
zeros = np.zeros((3,3,2),dtype=int)
ones = np.ones((3,3,4),dtype=int)
factor = 4 * ones
zeros,ones,factor

(array([[[0, 0],
         [0, 0],
         [0, 0]],
 
        [[0, 0],
         [0, 0],
         [0, 0]],
 
        [[0, 0],
         [0, 0],
         [0, 0]]]),
 array([[[1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1]],
 
        [[1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1]],
 
        [[1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1]]]),
 array([[[4, 4, 4, 4],
         [4, 4, 4, 4],
         [4, 4, 4, 4]],
 
        [[4, 4, 4, 4],
         [4, 4, 4, 4],
         [4, 4, 4, 4]],
 
        [[4, 4, 4, 4],
         [4, 4, 4, 4],
         [4, 4, 4, 4]]]))

In [12]:
# vector array
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
#linespace(start,step,end)
arr = np.linspace(0,20)

In [14]:
print(arr)

[ 0.          0.40816327  0.81632653  1.2244898   1.63265306  2.04081633
  2.44897959  2.85714286  3.26530612  3.67346939  4.08163265  4.48979592
  4.89795918  5.30612245  5.71428571  6.12244898  6.53061224  6.93877551
  7.34693878  7.75510204  8.16326531  8.57142857  8.97959184  9.3877551
  9.79591837 10.20408163 10.6122449  11.02040816 11.42857143 11.83673469
 12.24489796 12.65306122 13.06122449 13.46938776 13.87755102 14.28571429
 14.69387755 15.10204082 15.51020408 15.91836735 16.32653061 16.73469388
 17.14285714 17.55102041 17.95918367 18.36734694 18.7755102  19.18367347
 19.59183673 20.        ]


In [15]:
#random numbers
arr = np.random.rand(3,3,2)
arr

array([[[0.33250154, 0.72413815],
        [0.82050875, 0.45165444],
        [0.19817779, 0.76314061]],

       [[0.1167205 , 0.82370157],
        [0.40555655, 0.79427265],
        [0.76952521, 0.30329836]],

       [[0.52802949, 0.12389909],
        [0.57331883, 0.30613781],
        [0.40015129, 0.93012651]]])